import type {
  BeneficiariesResponse,
  BulkPayout,
  BulkPayoutBatch,
  BulkPayoutsResponse,
  Category,
  ChatItem,
  CheckoutLink,
  CheckoutLinkDetails,
  CustomerData,
  IDashboardAnalytics,
  IMerchant,
  IPayoutsAnalytics,
  IRevenueAnalytics,
  ISubscriptionAnalytics,
  ITransaction,
  IUser,
  Message,
  MonthlyPayoutPoint,
  Notification,
  Order,
  PayInKPIs,
  PayInTransaction,
  Product,
  SubscriptionItem,
  SubscriptionListResponse,
  Wallet,
  WalletBalanceSummary,
} from "./types"

export const mockMerchant: IMerchant = {
  id: "merchant_mock_001",
  name: "Xoro Demo Store",
  email: "demo@xoropay.com",
  is_verified: true,
  is_active: true,
  joined_at: "2026-01-12T09:00:00.000Z",
  test_balance: 2450000,
  live_balance: 1825000,
  percentage_charge: 1.5,
  flat_charge: 50,
  role: "owner",
}

export const mockUser: IUser = {
  id: "user_mock_001",
  name: "Demo Merchant",
  email: "demo@xoropay.com",
  created_at: "2026-01-12T09:00:00.000Z",
  updated_at: "2026-04-01T09:00:00.000Z",
  is_verified: true,
  merchants: [mockMerchant],
}

export const mockProducts: Product[] = [
  {
    id: "prod-001",
    name: "Wireless Payment Terminal",
    price: "NGN 185,000",
    stock: 24,
    category: "Hardware",
    sku: "XORO-HW-001",
    description: "Portable terminal for card and transfer collections.",
  },
  {
    id: "prod-002",
    name: "Checkout Starter Kit",
    price: "NGN 42,500",
    stock: 8,
    category: "Kits",
    sku: "XORO-KIT-002",
    description: "QR cards, counter display, and launch materials.",
  },
  {
    id: "prod-003",
    name: "Premium Support Plan",
    price: "NGN 75,000",
    stock: 100,
    category: "Services",
    sku: "XORO-SVC-003",
    description: "Priority setup and settlement support for larger teams.",
  },
]

export const mockCustomers: CustomerData[] = [
  {
    id: "cus-001",
    name: "Amina Bello",
    email: "amina@example.com",
    phone: "+234 801 555 0123",
    avatar: "AB",
    status: "active",
    totalOrders: 12,
    totalSpent: "NGN 840,000",
    joinDate: "Jan 12, 2026",
    lastPurchase: "Apr 02, 2026",
  },
  {
    id: "cus-002",
    name: "Tunde Martins",
    email: "tunde@example.com",
    phone: "+234 802 555 0178",
    avatar: "TM",
    status: "pending",
    totalOrders: 4,
    totalSpent: "NGN 220,000",
    joinDate: "Feb 04, 2026",
    lastPurchase: "Mar 28, 2026",
  },
  {
    id: "cus-003",
    name: "Nora Okafor",
    email: "nora@example.com",
    phone: "+234 803 555 0189",
    avatar: "NO",
    status: "active",
    totalOrders: 7,
    totalSpent: "NGN 515,500",
    joinDate: "Feb 18, 2026",
    lastPurchase: "Apr 06, 2026",
  },
]

export const mockOrders: Order[] = [
  {
    id: "ord-001",
    orderNumber: "ORD-1001",
    customerName: "Amina Bello",
    customerEmail: "amina@example.com",
    items: [
      { productName: "Wireless Payment Terminal", quantity: 1, price: "NGN 185,000" },
      { productName: "Checkout Starter Kit", quantity: 2, price: "NGN 85,000" },
    ],
    totalAmount: "NGN 270,000",
    status: "delivered",
    paymentStatus: "paid",
    orderDate: "Apr 02, 2026",
    shippingAddress: "12 Admiralty Way, Lekki, Lagos",
  },
  {
    id: "ord-002",
    orderNumber: "ORD-1002",
    customerName: "Tunde Martins",
    customerEmail: "tunde@example.com",
    items: [{ productName: "Premium Support Plan", quantity: 1, price: "NGN 75,000" }],
    totalAmount: "NGN 75,000",
    status: "processing",
    paymentStatus: "paid",
    orderDate: "Apr 05, 2026",
    shippingAddress: "8 Airport Road, Ikeja, Lagos",
  },
  {
    id: "ord-003",
    orderNumber: "ORD-1003",
    customerName: "Nora Okafor",
    customerEmail: "nora@example.com",
    items: [{ productName: "Checkout Starter Kit", quantity: 1, price: "NGN 42,500" }],
    totalAmount: "NGN 42,500",
    status: "pending",
    paymentStatus: "unpaid",
    orderDate: "Apr 06, 2026",
    shippingAddress: "21 Stadium Road, Port Harcourt",
  },
]

export const mockChats: ChatItem[] = [
  {
    id: "1",
    name: "Amina Bello",
    avatar: "AB",
    lastMessage: "Can I get the receipt for yesterday's payment?",
    timeAway: "5 min ago",
    unread: 2,
  },
  {
    id: "2",
    name: "Tunde Martins",
    avatar: "TM",
    lastMessage: "The transfer is still pending on my end.",
    timeAway: "18 min ago",
    unread: 0,
  },
  {
    id: "3",
    name: "Nora Okafor",
    avatar: "NO",
    lastMessage: "Please confirm the checkout link is active.",
    timeAway: "1 hour ago",
    unread: 1,
  },
]

export const mockMessages: Record<string, Message[]> = {
  "1": [
    { id: "m1", content: "Can I get the receipt for yesterday's payment?", timestamp: "09:42", isAgent: false },
    { id: "m2", content: "Yes, I can resend it to your email now.", timestamp: "09:44", isAgent: true },
  ],
  "2": [
    { id: "m3", content: "The transfer is still pending on my end.", timestamp: "08:12", isAgent: false },
    { id: "m4", content: "I am checking the settlement status.", timestamp: "08:14", isAgent: true },
  ],
  "3": [
    { id: "m5", content: "Please confirm the checkout link is active.", timestamp: "07:55", isAgent: false },
  ],
}

export const mockCustomersById: Record<string, CustomerData> = {
  "1": mockCustomers[0],
  "2": mockCustomers[1],
  "3": mockCustomers[2],
}

export const mockWallets: Wallet[] = [
  {
    id: 1,
    merchant_id: mockMerchant.id,
    currency: "NGN",
    balance: 2450000,
    mode: "test",
    percentage_charge: 1.5,
    flat_charge: 50,
    payout_percentage_charge: 1,
    payout_flat_charge: 25,
    is_active: true,
    created_at: "2026-01-12T09:00:00.000Z",
    updated_at: "2026-04-01T09:00:00.000Z",
  },
  {
    id: 2,
    merchant_id: mockMerchant.id,
    currency: "USD",
    balance: 12540,
    mode: "test",
    percentage_charge: 1.5,
    flat_charge: 0.5,
    payout_percentage_charge: 1,
    payout_flat_charge: 0.25,
    is_active: true,
    created_at: "2026-01-12T09:00:00.000Z",
    updated_at: "2026-04-01T09:00:00.000Z",
  },
]

export const mockWalletSummary: WalletBalanceSummary = {
  total_balance: 2462540,
}

export const mockDashboardAnalytics: IDashboardAnalytics = {
  mode: "test",
  period: "month",
  revenue_metrics: {
    total_revenue: 4825000,
    total_transactions: 1284,
    total_charges: 92500,
    net_revenue: 4732500,
    average_transaction_value: 3757,
    success_rate: 94.2,
  },
  transaction_breakdown: {
    successful: 1210,
    pending: 48,
    failed: 26,
    total: 1284,
  },
  top_currency: {
    currency: "NGN",
    total_revenue: 4825000,
    transaction_count: 1284,
    total_charges: 92500,
    net_revenue: 4732500,
    average_transaction_value: 3757,
  },
  wallet_count: 2,
  total_balance: 2462540,
  pending_payouts: 14,
  pending_payout_amount: 415000,
}

export const mockRevenueAnalytics: IRevenueAnalytics = {
  mode: "test",
  start_date: "2026-03-01",
  end_date: "2026-04-08",
  currency: "NGN",
  revenue_metrics: mockDashboardAnalytics.revenue_metrics,
  time_series: [
    { date: "2026-03-01", value: 620000, count: 142 },
    { date: "2026-03-08", value: 740000, count: 168 },
    { date: "2026-03-15", value: 810000, count: 192 },
    { date: "2026-03-22", value: 930000, count: 215 },
    { date: "2026-03-29", value: 1020000, count: 244 },
    { date: "2026-04-05", value: 705000, count: 161 },
  ],
  currency_breakdown: [mockDashboardAnalytics.top_currency!],
}

export const mockPayoutsAnalytics: IPayoutsAnalytics = {
  mode: "test",
  start_date: "2026-03-01",
  end_date: "2026-04-08",
  currency: "NGN",
  total_payouts: 2180000,
  payout_count: 184,
  successful_payouts: 169,
  failed_payouts: 4,
  pending_payouts: 11,
  total_payout_charges: 31200,
  average_payout_amount: 11847,
  time_series: [
    { date: "Jan", value: 340000, count: 42 },
    { date: "Feb", value: 420000, count: 51 },
    { date: "Mar", value: 680000, count: 63 },
    { date: "Apr", value: 740000, count: 28 },
  ],
}

export const mockNotifications: Notification[] = [
  {
    id: "1",
    title: "New order received",
    description: "Order #ORD-011 from Sarah Johnson for â‚¦45,000",
    timestamp: "2 mins ago",
    read: false,
    type: "order",
  },
  {
    id: "2",
    title: "Low stock alert",
    description: "Mechanical Keyboard (SKU: PROD-006) has only 5 units left",
    timestamp: "15 mins ago",
    read: false,
    type: "warning",
  },
  {
    id: "3",
    title: "Payment confirmed",
    description: "Payment of â‚¦22,500 received for order #ORD-004",
    timestamp: "1 hour ago",
    read: false,
    type: "success",
  },
  {
    id: "4",
    title: "Order shipped",
    description: "Order #ORD-007 has been shipped to Jennifer Martinez",
    timestamp: "3 hours ago",
    read: true,
    type: "info",
  },
  {
    id: "5",
    title: "New customer registered",
    description: "Rachel Allen created an account",
    timestamp: "5 hours ago",
    read: true,
    type: "info",
  },
  {
    id: "6",
    title: "Order delivered",
    description: "Order #ORD-001 was delivered successfully",
    timestamp: "1 day ago",
    read: true,
    type: "success",
  },
]

export const mockBalanceTransactions = [
  {
    id: "1",
    type: "Payout",
    reference: "#TRX-948201",
    amount: "$2,500.00",
    currency: "USD",
    paymentMethod: "Transfer",
    status: "Completed",
    date: "Oct 24, 2023, 14:20",
  },
  {
    id: "2",
    type: "Sales Income",
    reference: "#TRX-948199",
    amount: "$120.50",
    currency: "USD",
    paymentMethod: "Card",
    status: "Pending",
    date: "Oct 24, 2023, 11:05",
  },
  {
    id: "3",
    type: "Refund",
    reference: "#TRX-948190",
    amount: "-$45.00",
    currency: "USD",
    paymentMethod: "Card",
    status: "Completed",
    date: "Oct 23, 2023, 09:45",
  },
  {
    id: "4",
    type: "Sales Income",
    reference: "#TRX-948185",
    amount: "$1,100.00",
    currency: "USD",
    paymentMethod: "Mobile Money",
    status: "Completed",
    date: "Oct 23, 2023, 08:30",
  },
  {
    id: "5",
    type: "Payout",
    reference: "#TRX-948170",
    amount: "$4,000.00",
    currency: "USD",
    paymentMethod: "Crypto",
    status: "Completed",
    date: "Oct 22, 2023, 16:15",
  },
  {
    id: "6",
    type: "Top-up",
    reference: "#TRX-948160",
    amount: "$500.00",
    currency: "USD",
    paymentMethod: "Card",
    status: "Completed",
    date: "Oct 22, 2023, 10:00",
  },
  {
    id: "7",
    type: "Sales Income",
    reference: "#TRX-948155",
    amount: "₦340,000.00",
    currency: "NGN",
    paymentMethod: "Transfer",
    status: "Pending",
    date: "Oct 21, 2023, 14:30",
  },
  {
    id: "8",
    type: "Refund",
    reference: "#TRX-948150",
    amount: "-$12.50",
    currency: "USD",
    paymentMethod: "Card",
    status: "Failed",
    date: "Oct 21, 2023, 09:15",
  },
  {
    id: "9",
    type: "Payout",
    reference: "#TRX-948145",
    amount: "€1,200.00",
    currency: "EUR",
    paymentMethod: "Transfer",
    status: "Completed",
    date: "Oct 20, 2023, 11:45",
  },
  {
    id: "10",
    type: "Sales Income",
    reference: "#TRX-948140",
    amount: "₮890.00",
    currency: "USDT",
    paymentMethod: "Crypto",
    status: "Completed",

    date: "Oct 19, 2023, 16:20",
  },
  {
    id: "11",
    type: "Sales Income",
    reference: "#TRX-948135",
    amount: "$430.00",
    currency: "USD",
    paymentMethod: "Mobile Money",
    status: "Completed",
    date: "Oct 19, 2023, 12:10",
  },
  {
    id: "12",
    type: "Payout",
    reference: "#TRX-948130",
    amount: "₦3,000,000.00",
    currency: "NGN",
    paymentMethod: "Transfer",
    status: "Completed",
    date: "Oct 18, 2023, 09:00",
  },
]

export const mockBulkPayoutRows: BulkPayoutBatch[] = [
  {
    id: "batch-1",
    batchName: "March Vendor Payouts",
    reference: "BP-2023-03-A",
    transactions: 145,
    amount: "45,230.50",
    status: "Success",
    createdAt: "Oct 24, 2023, 16:45",
  },
  {
    id: "batch-2",
    batchName: "Affiliate Commission Q3",
    reference: "BP-2023-03-B",
    transactions: 89,
    amount: "12,450.00",
    status: "Success",
    createdAt: "Oct 23, 2023, 14:20",
  },
  {
    id: "batch-3",
    batchName: "Contractor Weekly",
    reference: "BP-2023-03-C",
    transactions: 24,
    amount: "8,900.25",
    status: "Pending",
    createdAt: "Oct 22, 2023, 09:15",
  },
  {
    id: "batch-4",
    batchName: "Refund processing batch",
    reference: "BP-2023-03-D",
    transactions: 12,
    amount: "1,250.00",
    status: "Partial",
    createdAt: "Oct 21, 2023, 11:30",
  },
  {
    id: "batch-5",
    batchName: "Salary Advances",
    reference: "BP-2023-03-E",
    transactions: 5,
    amount: "4,500.00",
    status: "Failed",
    createdAt: "Oct 20, 2023, 10:00",
  },
  {
    id: "batch-6",
    batchName: "Bonus Payouts",
    reference: "BP-2023-03-F",
    transactions: 300,
    amount: "150,000.00",
    status: "Success",
    createdAt: "Oct 19, 2023, 15:45",
  },
  {
    id: "batch-7",
    batchName: "Vendor Adjustments",
    reference: "BP-2023-03-G",
    transactions: 8,
    amount: "840.00",
    status: "Success",
    createdAt: "Oct 18, 2023, 12:10",
  },
]

export const mockBeneficiaries: import("./types").Beneficiary[] = []

export const mockMonthlyPayoutVolume: MonthlyPayoutPoint[] = [
  { month: "Jan", value: 340000, payoutCount: 1240 },
  { month: "Feb", value: 420000, payoutCount: 1450 },
  { month: "Mar", value: 280000, payoutCount: 1100 },
  { month: "Apr", value: 500000, payoutCount: 1800 },
  { month: "May", value: 650000, payoutCount: 2200 },
  { month: "Jun", value: 480000, payoutCount: 1650 },
  { month: "Jul", value: 550000, payoutCount: 1900 },
  { month: "Aug", value: 720000, payoutCount: 2500 },
  { month: "Sep", value: 680000, payoutCount: 2300 },
  { month: "Oct", value: 850000, payoutCount: 2800 },
  { month: "Nov", value: 0, payoutCount: 0 },
  { month: "Dec", value: 0, payoutCount: 0 },
]

export const mockMerchantTransactions = {
  transactions: [
    {
      id: "txn-001",
      type: "Sales Income",
      reference: "TRX-MOCK-001",
      amount: "NGN 185,000.00",
      currency: "NGN",
      paymentMethod: "Card",
      status: "Completed",
      date: "Apr 08, 2026, 09:20",
    },
    {
      id: "txn-002",
      type: "Payout",
      reference: "TRX-MOCK-002",
      amount: "NGN 75,000.00",
      currency: "NGN",
      paymentMethod: "Transfer",
      status: "Pending",
      date: "Apr 07, 2026, 16:10",
    },
    {
      id: "txn-003",
      type: "Refund",
      reference: "TRX-MOCK-003",
      amount: "-NGN 42,500.00",
      currency: "NGN",
      paymentMethod: "Card",
      status: "Failed",
      date: "Apr 06, 2026, 11:35",
    },
  ],
  total_items: 3,
  total_pages: 1,
  current_page: 1,
  page_size: 10,
}

export const mockBulkPayouts: BulkPayout[] = [
  {
    id: 1,
    name: "April Vendor Payouts",
    reference: "BP-MOCK-001",
    status: "success",
    transaction_details: [
      { txn_id: 101, txn_message: "Paid", status: true },
      { txn_id: 102, txn_message: "Paid", status: true },
    ],
    created_at: "Apr 08, 2026, 10:00",
  },
  {
    id: 2,
    name: "Affiliate Commission Batch",
    reference: "BP-MOCK-002",
    status: "pending",
    transaction_details: [
      { txn_id: 103, txn_message: "Processing", status: true },
    ],
    created_at: "Apr 07, 2026, 15:30",
  },
]

export const mockBulkPayoutsResponse: BulkPayoutsResponse = {
  payouts: mockBulkPayouts,
  total_items: mockBulkPayouts.length,
  total_pages: 1,
  current_page: 1,
  page_size: 10,
  pending_count: 1,
  success_count: 1,
  partial_count: 0,
  failed_count: 0,
  success_rate: 50,
}

export const mockCategories: Category[] = [
  {
    id: 1,
    name: "Vendors",
    description: "Approved vendor payout accounts",
    merchant_id: mockMerchant.id,
  },
  {
    id: 2,
    name: "Contractors",
    description: "Recurring contractor payouts",
    merchant_id: mockMerchant.id,
  },
]

export const mockBeneficiariesResponse: BeneficiariesResponse = {
  beneficiaries: [
    {
      id: 1,
      name: "Kemi Supplies Ltd",
      email: "accounts@kemi.example",
      merchant_id: mockMerchant.id,
      bank_code: "044",
      account_number: "0123456789",
      phone_number: "+234 801 555 0101",
      whatsapp_number: "+234 801 555 0101",
      default_amount: 125000,
      narration: "Monthly vendor payment",
      is_active: true,
      category_id: 1,
      created_at: "2026-03-01T09:00:00.000Z",
      updated_at: "2026-04-01T09:00:00.000Z",
    },
    {
      id: 2,
      name: "Northstar Logistics",
      email: "ops@northstar.example",
      merchant_id: mockMerchant.id,
      bank_code: "058",
      account_number: "9876543210",
      phone_number: "+234 802 555 0102",
      whatsapp_number: "+234 802 555 0102",
      default_amount: 84500,
      narration: "Delivery settlement",
      is_active: true,
      category_id: 2,
      created_at: "2026-03-05T09:00:00.000Z",
      updated_at: "2026-04-02T09:00:00.000Z",
    },
  ],
  current_page: 1,
  page_size: 10,
  total_items: 2,
  total_pages: 1,
}

export const mockTransactions: ITransaction[] = [
  {
    id: 1,
    type: "credit",
    status: "success",
    mode: "test",
    amount: 185000,
    charge: 2775,
    processor_reference: "PROC-MOCK-001",
    reference: "PAY-MOCK-001",
    customer: { name: "Amina Bello", email: "amina@example.com" },
    created_at: "2026-04-08T09:20:00.000Z",
  },
  {
    id: 2,
    type: "credit",
    status: "pending",
    mode: "test",
    amount: 75000,
    charge: 1125,
    processor_reference: "PROC-MOCK-002",
    reference: "PAY-MOCK-002",
    customer: { name: "Tunde Martins", email: "tunde@example.com" },
    created_at: "2026-04-07T16:10:00.000Z",
  },
]

export const mockCheckoutLinks: CheckoutLink[] = [
  {
    id: "link-001",
    reference: "CHK-MOCK-001",
    title: "Starter Kit Checkout",
    merchant_id: mockMerchant.id,
    url: "https://pay.xoro.example/CHK-MOCK-001",
    description: "Payment link for checkout starter kits.",
    amount_type: "static",
    mode: "test",
    type: "one_time",
    currency: "NGN",
    amount: 42500,
    max_uses: 100,
    current_uses: 38,
    redirect_url: null,
    expires_at: "2026-06-30T23:59:59.000Z",
    is_active: true,
    created_at: "2026-03-18T09:00:00.000Z",
    updated_at: "2026-04-02T09:00:00.000Z",
  },
  {
    id: "link-002",
    reference: "CHK-MOCK-002",
    title: "Flexible Invoice",
    merchant_id: mockMerchant.id,
    url: "https://pay.xoro.example/CHK-MOCK-002",
    description: "Flexible invoice collection link.",
    amount_type: "dynamic",
    mode: "test",
    type: "one_time",
    currency: "NGN",
    amount: null,
    max_uses: null,
    current_uses: 21,
    redirect_url: null,
    expires_at: "2026-06-30T23:59:59.000Z",
    is_active: true,
    created_at: "2026-03-22T09:00:00.000Z",
    updated_at: "2026-04-04T09:00:00.000Z",
  },
]

export const mockCheckoutLinkDetails: CheckoutLinkDetails[] = mockCheckoutLinks.map(
  (link) => ({
    ...link,
    transactions: mockTransactions,
  }),
)

export const mockSubscriptionItems: SubscriptionItem[] = [
  {
    id: "sub-001",
    merchant_id: mockMerchant.id,
    product_id: "plan-growth",
    customer_id: "cus-001",
    subscriber_id: "subscriber-001",
    subscriber_email: "amina@example.com",
    subscriber_name: "Amina Bello",
    subscriber_phone: "+234 801 555 0123",
    status: "active",
    current_period_start: "2026-04-01T00:00:00.000Z",
    current_period_end: "2026-05-01T00:00:00.000Z",
    grace_period_days: 3,
    grace_period_end: null,
    trial_end: null,
    cancelled_at: null,
    cancel_at_period_end: false,
    cancellation_reason: null,
    paused_at: null,
    price_override: 25000,
    metadata: null,
    external_id: null,
    bulk_subscription_id: null,
    created_at: "2026-01-12T09:00:00.000Z",
    updated_at: "2026-04-01T09:00:00.000Z",
  },
  {
    id: "sub-002",
    merchant_id: mockMerchant.id,
    product_id: "plan-growth",
    customer_id: "cus-002",
    subscriber_id: "subscriber-002",
    subscriber_email: "tunde@example.com",
    subscriber_name: "Tunde Martins",
    subscriber_phone: "+234 802 555 0178",
    status: "past_due",
    current_period_start: "2026-03-15T00:00:00.000Z",
    current_period_end: "2026-04-15T00:00:00.000Z",
    grace_period_days: 5,
    grace_period_end: "2026-04-20T00:00:00.000Z",
    trial_end: null,
    cancelled_at: null,
    cancel_at_period_end: false,
    cancellation_reason: null,
    paused_at: null,
    price_override: 25000,
    metadata: null,
    external_id: null,
    bulk_subscription_id: null,
    created_at: "2026-02-04T09:00:00.000Z",
    updated_at: "2026-04-05T09:00:00.000Z",
  },
  {
    id: "sub-003",
    merchant_id: mockMerchant.id,
    product_id: "plan-scale",
    customer_id: "cus-003",
    subscriber_id: "subscriber-003",
    subscriber_email: "nora@example.com",
    subscriber_name: "Nora Okafor",
    subscriber_phone: "+234 803 555 0189",
    status: "active",
    current_period_start: "2026-04-06T00:00:00.000Z",
    current_period_end: "2026-05-06T00:00:00.000Z",
    grace_period_days: 3,
    grace_period_end: null,
    trial_end: null,
    cancelled_at: null,
    cancel_at_period_end: false,
    cancellation_reason: null,
    paused_at: null,
    price_override: 50000,
    metadata: null,
    external_id: null,
    bulk_subscription_id: null,
    created_at: "2026-03-18T09:00:00.000Z",
    updated_at: "2026-04-06T09:00:00.000Z",
  },
]

export const mockSubscriptionListResponse: SubscriptionListResponse = {
  items: mockSubscriptionItems,
  total: mockSubscriptionItems.length,
  page: 1,
  page_size: 20,
  total_pages: 1,
}

export const mockSubscriptionAnalytics: ISubscriptionAnalytics = {
  total: mockSubscriptionItems.length,
  active: 2,
  pending: 0,
  past_due: 1,
  grace: 0,
  expired: 0,
  cancelled: 0,
  paused: 0,
}

export const mockPayInKPIs: PayInKPIs = {
  totalVolume: "$124,500.00",
  transactionCount: "1,284",
  averagePayIn: "$96.96",
  volumeChange: "+12.5%",
  countChange: "+5.2%",
}

export const mockPayInTransactions: PayInTransaction[] = [
  { id: "1", customerName: "John Doe", email: "john@example.com", reference: "TRu-992831", amount: "$120.00", method: "Card", status: "Success", date: "Oct 24, 2023" },
  { id: "2", customerName: "Alice Smith", email: "alice@tech.io", reference: "TRu-882732", amount: "$450.00", method: "Transfer", status: "Pending", date: "Oct 24, 2023" },
  { id: "3", customerName: "Crypto Whale", email: "whale@btc.com", reference: "TRu-772103", amount: "0.05 BTC", method: "Crypto", status: "Success", date: "Oct 23, 2023" },
  { id: "4", customerName: "Bob Johnson", email: "bob@corp.com", reference: "TRu-662544", amount: "$85.50", method: "Card", status: "Failed", date: "Oct 23, 2023" },
  { id: "5", customerName: "Sarah Williams", email: "sarah@williams.net", reference: "TRu-552985", amount: "$1,200.00", method: "Transfer", status: "Success", date: "Oct 22, 2023" },
]

export const mockPayOutKPIs: import("./types").PayOutKPIs = {
  totalPaid: "$124,500.00",
  pendingProcessing: "$12,450.25",
  failedPayouts: "2",
}

export const mockPayOutTransactions: import("./types").PayOutTransaction[] = [
  { id: "1", recipientName: "Acme Corp", recipientType: "Business Services", reference: "Inv-001", amount: "$1,200.00", method: "Bank Transfer", status: "Completed", date: "Oct 24, 2023" },
  { id: "2", recipientName: "Global Logistics", recipientType: "Shipping", reference: "Shipping Fees", amount: "$450.25", method: "Xoro Wallet", status: "Pending", date: "Oct 25, 2023" },
  { id: "3", recipientName: "Tech Solutions", recipientType: "Software", reference: "Subscription", amount: "$89.00", method: "Card Payout", status: "Completed", date: "Oct 25, 2023" },
  { id: "4", recipientName: "Refund - User 88", recipientType: "Customer Refund", reference: "Order #992", amount: "$55.00", method: "Xoro Wallet", status: "Processing", date: "Oct 26, 2023" },
  { id: "5", recipientName: "Marketing Agency", recipientType: "Advertising", reference: "Ad Spend", amount: "$3,000.00", method: "Bank Transfer", status: "Failed", date: "Oct 26, 2023" },
]

export const getDetailedPlanSubscription = (id: string): import("./types").DetailedPlanSubscription => ({
  id,
  planName: "Premium Monthly",
  price: "₦5,000",
  billingCycle: "Monthly",
  trialPeriod: "None",
  createdDate: "Jan 12, 2026",
  totalSubscribers: 5235,
  activeSubscribers: 5012,
  monthlyRevenue: "₦42,500.00",
  churnRate: "1.4%",
  healthStats: {
    active: 95,
    cancelled: 3,
    pastDue: 2,
  },
  recentActivity: [
    { id: "1", type: "renewed", title: "Subscription renewed", timestamp: "Feb 12, 2026 • 09:41 AM" },
    { id: "2", type: "successful", title: "Payment successful", timestamp: "Jan 12, 2026 • 11:20 AM" },
    { id: "3", type: "created", title: "Subscription created", timestamp: "Jan 12, 2026 • 11:15 AM" },
  ],
  subscribers: [
    { id: "sub-1", customerName: "John Doe", email: "john@example.com", planType: "Premium", status: "Active", nextBillingDate: "Feb 12", amount: "₦5,000" },
    { id: "sub-2", customerName: "Sarah Smith", email: "sarah@corp.com", planType: "Premium", status: "Past Due", nextBillingDate: "Jan 15", amount: "₦5,000" },
  ]
})

export const mockRefundKPIs: import("./types").RefundKPIs = {
  pending: "12 Requests",
  processing: "4 Requests",
  completed: "184 Today",
  failed: "2 Issues",
}

export const mockRefundRequests: import("./types").RefundRequest[] = [
  { id: "1", customerName: "Alex Rivera", avatarColor: "bg-surface-2 text-brand-primary-2", transactionId: "#XP-90210", amount: "$120.00", reason: "Defective item", status: "Completed", date: "Oct 24, 2023" },

  { id: "2", customerName: "Sarah Chen", avatarColor: "bg-accent-blue", transactionId: "#XP-88342", amount: "$45.50", reason: "Accidental purchase", status: "Processing", date: "Oct 23, 2023" },
  { id: "3", customerName: "Mike Johnson", avatarColor: "bg-surface-6", transactionId: "#XP-77219", amount: "$299.00", reason: "Not as described", status: "Completed", date: "Oct 22, 2023" },
  { id: "4", customerName: "Emily Davis", avatarColor: "bg-status-danger", transactionId: "#XP-66102", amount: "$15.00", reason: "Late delivery", status: "Failed", date: "Oct 21, 2023" },
  { id: "5", customerName: "Robert Wilson", avatarColor: "bg-status-warning", transactionId: "#XP-55091", amount: "$89.99", reason: "Changed mind", status: "Pending", date: "Oct 20, 2023" },
]
