import type {
  BalanceTransaction,
  BulkPayoutBatch,
  MonthlyPayoutPoint,
  Notification,
  PayInKPIs,
  PayInTransaction,
} from "./types"

export const mockNotifications: Notification[] = [
  {
    id: "1",
    title: "New order received",
    description: "Order #ORD-011 from Sarah Johnson for â‚¦45,000",
    timestamp: "2 mins ago",
    read: false,
    type: "order",
  },
  {
    id: "2",
    title: "Low stock alert",
    description: "Mechanical Keyboard (SKU: PROD-006) has only 5 units left",
    timestamp: "15 mins ago",
    read: false,
    type: "warning",
  },
  {
    id: "3",
    title: "Payment confirmed",
    description: "Payment of â‚¦22,500 received for order #ORD-004",
    timestamp: "1 hour ago",
    read: false,
    type: "success",
  },
  {
    id: "4",
    title: "Order shipped",
    description: "Order #ORD-007 has been shipped to Jennifer Martinez",
    timestamp: "3 hours ago",
    read: true,
    type: "info",
  },
  {
    id: "5",
    title: "New customer registered",
    description: "Rachel Allen created an account",
    timestamp: "5 hours ago",
    read: true,
    type: "info",
  },
  {
    id: "6",
    title: "Order delivered",
    description: "Order #ORD-001 was delivered successfully",
    timestamp: "1 day ago",
    read: true,
    type: "success",
  },
]

export const mockBalanceTransactions: BalanceTransaction[] = [
  {
    id: "1",
    type: "Payout",
    reference: "#TRX-948201",
    amount: "$2,500.00",
    currency: "USD",
    paymentMethod: "Transfer",
    status: "Completed",
    date: "Oct 24, 2023, 14:20",
  },
  {
    id: "2",
    type: "Sales Income",
    reference: "#TRX-948199",
    amount: "$120.50",
    currency: "USD",
    paymentMethod: "Card",
    status: "Pending",
    date: "Oct 24, 2023, 11:05",
  },
  {
    id: "3",
    type: "Refund",
    reference: "#TRX-948190",
    amount: "-$45.00",
    currency: "USD",
    paymentMethod: "Card",
    status: "Completed",
    date: "Oct 23, 2023, 09:45",
  },
  {
    id: "4",
    type: "Sales Income",
    reference: "#TRX-948185",
    amount: "$1,100.00",
    currency: "USD",
    paymentMethod: "Mobile Money",
    status: "Completed",
    date: "Oct 23, 2023, 08:30",
  },
  {
    id: "5",
    type: "Payout",
    reference: "#TRX-948170",
    amount: "$4,000.00",
    currency: "USD",
    paymentMethod: "Crypto",
    status: "Completed",
    date: "Oct 22, 2023, 16:15",
  },
  {
    id: "6",
    type: "Top-up",
    reference: "#TRX-948160",
    amount: "$500.00",
    currency: "USD",
    paymentMethod: "Card",
    status: "Completed",
    date: "Oct 22, 2023, 10:00",
  },
  {
    id: "7",
    type: "Sales Income",
    reference: "#TRX-948155",
    amount: "₦340,000.00",
    currency: "NGN",
    paymentMethod: "Transfer",
    status: "Pending",
    date: "Oct 21, 2023, 14:30",
  },
  {
    id: "8",
    type: "Refund",
    reference: "#TRX-948150",
    amount: "-$12.50",
    currency: "USD",
    paymentMethod: "Card",
    status: "Failed",
    date: "Oct 21, 2023, 09:15",
  },
  {
    id: "9",
    type: "Payout",
    reference: "#TRX-948145",
    amount: "€1,200.00",
    currency: "EUR",
    paymentMethod: "Transfer",
    status: "Completed",
    date: "Oct 20, 2023, 11:45",
  },
  {
    id: "10",
    type: "Sales Income",
    reference: "#TRX-948140",
    amount: "₮890.00",
    currency: "USDT",
    paymentMethod: "Crypto",
    status: "Completed",

    date: "Oct 19, 2023, 16:20",
  },
  {
    id: "11",
    type: "Sales Income",
    reference: "#TRX-948135",
    amount: "$430.00",
    currency: "USD",
    paymentMethod: "Mobile Money",
    status: "Completed",
    date: "Oct 19, 2023, 12:10",
  },
  {
    id: "12",
    type: "Payout",
    reference: "#TRX-948130",
    amount: "₦3,000,000.00",
    currency: "NGN",
    paymentMethod: "Transfer",
    status: "Completed",
    date: "Oct 18, 2023, 09:00",
  },
]

export const mockBulkPayoutRows: BulkPayoutBatch[] = [
  {
    id: "batch-1",
    batchName: "March Vendor Payouts",
    reference: "BP-2023-03-A",
    transactions: 145,
    amount: "45,230.50",
    status: "Success",
    createdAt: "Oct 24, 2023, 16:45",
  },
  {
    id: "batch-2",
    batchName: "Affiliate Commission Q3",
    reference: "BP-2023-03-B",
    transactions: 89,
    amount: "12,450.00",
    status: "Success",
    createdAt: "Oct 23, 2023, 14:20",
  },
  {
    id: "batch-3",
    batchName: "Contractor Weekly",
    reference: "BP-2023-03-C",
    transactions: 24,
    amount: "8,900.25",
    status: "Pending",
    createdAt: "Oct 22, 2023, 09:15",
  },
  {
    id: "batch-4",
    batchName: "Refund processing batch",
    reference: "BP-2023-03-D",
    transactions: 12,
    amount: "1,250.00",
    status: "Partial",
    createdAt: "Oct 21, 2023, 11:30",
  },
  {
    id: "batch-5",
    batchName: "Salary Advances",
    reference: "BP-2023-03-E",
    transactions: 5,
    amount: "4,500.00",
    status: "Failed",
    createdAt: "Oct 20, 2023, 10:00",
  },
  {
    id: "batch-6",
    batchName: "Bonus Payouts",
    reference: "BP-2023-03-F",
    transactions: 300,
    amount: "150,000.00",
    status: "Success",
    createdAt: "Oct 19, 2023, 15:45",
  },
  {
    id: "batch-7",
    batchName: "Vendor Adjustments",
    reference: "BP-2023-03-G",
    transactions: 8,
    amount: "840.00",
    status: "Success",
    createdAt: "Oct 18, 2023, 12:10",
  },
]

export const mockBeneficiaries: import("./types").Beneficiary[] = []

export const mockMonthlyPayoutVolume: MonthlyPayoutPoint[] = [
  { month: "Jan", value: 340000, payoutCount: 1240 },
  { month: "Feb", value: 420000, payoutCount: 1450 },
  { month: "Mar", value: 280000, payoutCount: 1100 },
  { month: "Apr", value: 500000, payoutCount: 1800 },
  { month: "May", value: 650000, payoutCount: 2200 },
  { month: "Jun", value: 480000, payoutCount: 1650 },
  { month: "Jul", value: 550000, payoutCount: 1900 },
  { month: "Aug", value: 720000, payoutCount: 2500 },
  { month: "Sep", value: 680000, payoutCount: 2300 },
  { month: "Oct", value: 850000, payoutCount: 2800 },
  { month: "Nov", value: 0, payoutCount: 0 },
  { month: "Dec", value: 0, payoutCount: 0 },
]

export const mockPayInKPIs: PayInKPIs = {
  totalVolume: "$124,500.00",
  transactionCount: "1,284",
  averagePayIn: "$96.96",
  volumeChange: "+12.5%",
  countChange: "+5.2%",
}

export const mockPayInTransactions: PayInTransaction[] = [
  { id: "1", customerName: "John Doe", email: "john@example.com", reference: "TRu-992831", amount: "$120.00", method: "Card", status: "Success", date: "Oct 24, 2023" },
  { id: "2", customerName: "Alice Smith", email: "alice@tech.io", reference: "TRu-882732", amount: "$450.00", method: "Transfer", status: "Pending", date: "Oct 24, 2023" },
  { id: "3", customerName: "Crypto Whale", email: "whale@btc.com", reference: "TRu-772103", amount: "0.05 BTC", method: "Crypto", status: "Success", date: "Oct 23, 2023" },
  { id: "4", customerName: "Bob Johnson", email: "bob@corp.com", reference: "TRu-662544", amount: "$85.50", method: "Card", status: "Failed", date: "Oct 23, 2023" },
  { id: "5", customerName: "Sarah Williams", email: "sarah@williams.net", reference: "TRu-552985", amount: "$1,200.00", method: "Transfer", status: "Success", date: "Oct 22, 2023" },
]

export const getDetailedPlanSubscription = (id: string): import("./types").DetailedPlanSubscription => ({
  id,
  planName: "Premium Monthly",
  price: "₦5,000",
  billingCycle: "Monthly",
  trialPeriod: "None",
  createdDate: "Jan 12, 2026",
  totalSubscribers: 5235,
  activeSubscribers: 5012,
  monthlyRevenue: "₦42,500.00",
  churnRate: "1.4%",
  healthStats: {
    active: 95,
    cancelled: 3,
    pastDue: 2,
  },
  recentActivity: [
    { id: "1", type: "renewed", title: "Subscription renewed", timestamp: "Feb 12, 2026 • 09:41 AM" },
    { id: "2", type: "successful", title: "Payment successful", timestamp: "Jan 12, 2026 • 11:20 AM" },
    { id: "3", type: "created", title: "Subscription created", timestamp: "Jan 12, 2026 • 11:15 AM" },
  ],
  subscribers: [
    { id: "sub-1", customerName: "John Doe", email: "john@example.com", planType: "Premium", status: "Active", nextBillingDate: "Feb 12", amount: "₦5,000" },
    { id: "sub-2", customerName: "Sarah Smith", email: "sarah@corp.com", planType: "Premium", status: "Past Due", nextBillingDate: "Jan 15", amount: "₦5,000" },
  ]
})
