import { ChatItem, CustomerData, Message, Notification, Order, Product } from "@/lib/types";

export const mockChats: ChatItem[] = [
	{
		id: "1",
		name: "Sarah Johnson",
		avatar: "SJ",
		lastMessage: "Thanks for your help!",
		timeAway: "Just now",
		unread: 2,
	},
	{
		id: "2",
		name: "Michael Chen",
		avatar: "MC",
		lastMessage: "Can you help me with my order?",
		timeAway: "2 mins ago",
		unread: 1,
	},
	{
		id: "3",
		name: "Emma Davis",
		avatar: "ED",
		lastMessage: "Perfect, I'll proceed with the purchase",
		timeAway: "15 mins ago",
		unread: 0,
	},
	{
		id: "4",
		name: "James Wilson",
		avatar: "JW",
		lastMessage: "Is the product still available?",
		timeAway: "1 hour ago",
		unread: 0,
	},
	{
		id: "5",
		name: "Lisa Anderson",
		avatar: "LA",
		lastMessage: "Thank you for the quick response",
		timeAway: "3 hours ago",
		unread: 0,
	},
];

export const mockCustomers: CustomerData[] = [
	{
		id: "1",
		name: "Sarah Johnson",
		avatar: "SJ",
		email: "sarah.johnson@email.com",
		phone: "+1 (555) 123-4567",
		joinDate: "March 15, 2023",
		totalOrders: 12,
		totalSpent: "₦45,000",
		lastPurchase: "January 10, 2026",
		status: "active",
	},
	{
		id: "2",
		name: "Michael Chen",
		avatar: "MC",
		email: "michael.chen@email.com",
		phone: "+1 (555) 234-5678",
		joinDate: "June 22, 2023",
		totalOrders: 8,
		totalSpent: "₦28,500",
		lastPurchase: "January 12, 2026",
		status: "active",
	},
	{
		id: "3",
		name: "Emma Davis",
		avatar: "ED",
		email: "emma.davis@email.com",
		phone: "+1 (555) 345-6789",
		joinDate: "September 10, 2023",
		totalOrders: 5,
		totalSpent: "₦18,000",
		lastPurchase: "January 14, 2026",
		status: "pending",
	},
	{
		id: "4",
		name: "James Wilson",
		avatar: "JW",
		email: "james.wilson@email.com",
		phone: "+1 (555) 456-7890",
		joinDate: "December 5, 2023",
		totalOrders: 3,
		totalSpent: "₦9,500",
		lastPurchase: "January 8, 2026",
		status: "inactive",
	},
	{
		id: "5",
		name: "Lisa Anderson",
		avatar: "LA",
		email: "lisa.anderson@email.com",
		phone: "+1 (555) 567-8901",
		joinDate: "January 20, 2024",
		totalOrders: 15,
		totalSpent: "₦62,000",
		lastPurchase: "January 15, 2026",
		status: "active",
	},
	{
		id: "6",
		name: "David Brown",
		avatar: "DB",
		email: "david.brown@email.com",
		phone: "+1 (555) 678-9012",
		joinDate: "February 8, 2024",
		totalOrders: 7,
		totalSpent: "₦31,200",
		lastPurchase: "January 16, 2026",
		status: "active",
	},
	{
		id: "7",
		name: "Jennifer Martinez",
		avatar: "JM",
		email: "jennifer.martinez@email.com",
		phone: "+1 (555) 789-0123",
		joinDate: "March 12, 2024",
		totalOrders: 22,
		totalSpent: "₦89,000",
		lastPurchase: "January 17, 2026",
		status: "active",
	},
	{
		id: "8",
		name: "Robert Taylor",
		avatar: "RT",
		email: "robert.taylor@email.com",
		phone: "+1 (555) 890-1234",
		joinDate: "April 5, 2024",
		totalOrders: 4,
		totalSpent: "₦15,800",
		lastPurchase: "December 20, 2025",
		status: "pending",
	},
	{
		id: "9",
		name: "Amanda White",
		avatar: "AW",
		email: "amanda.white@email.com",
		phone: "+1 (555) 901-2345",
		joinDate: "May 18, 2024",
		totalOrders: 9,
		totalSpent: "₦42,300",
		lastPurchase: "January 11, 2026",
		status: "active",
	},
	{
		id: "10",
		name: "Christopher Lee",
		avatar: "CL",
		email: "christopher.lee@email.com",
		phone: "+1 (555) 012-3456",
		joinDate: "June 25, 2024",
		totalOrders: 1,
		totalSpent: "₦5,500",
		lastPurchase: "November 15, 2025",
		status: "inactive",
	},
	{
		id: "11",
		name: "Michelle Garcia",
		avatar: "MG",
		email: "michelle.garcia@email.com",
		phone: "+1 (555) 123-4568",
		joinDate: "July 8, 2024",
		totalOrders: 18,
		totalSpent: "₦76,400",
		lastPurchase: "January 16, 2026",
		status: "active",
	},
	{
		id: "12",
		name: "Daniel Robinson",
		avatar: "DR",
		email: "daniel.robinson@email.com",
		phone: "+1 (555) 234-5679",
		joinDate: "August 14, 2024",
		totalOrders: 6,
		totalSpent: "₦24,100",
		lastPurchase: "January 5, 2026",
		status: "active",
	},
	{
		id: "13",
		name: "Ashley Thompson",
		avatar: "AT",
		email: "ashley.thompson@email.com",
		phone: "+1 (555) 345-6780",
		joinDate: "September 3, 2024",
		totalOrders: 11,
		totalSpent: "₦51,700",
		lastPurchase: "January 14, 2026",
		status: "active",
	},
	{
		id: "14",
		name: "Kevin Harris",
		avatar: "KH",
		email: "kevin.harris@email.com",
		phone: "+1 (555) 456-7891",
		joinDate: "October 22, 2024",
		totalOrders: 2,
		totalSpent: "₦8,200",
		lastPurchase: "December 28, 2025",
		status: "pending",
	},
	{
		id: "15",
		name: "Stephanie Clark",
		avatar: "SC",
		email: "stephanie.clark@email.com",
		phone: "+1 (555) 567-8902",
		joinDate: "November 11, 2024",
		totalOrders: 14,
		totalSpent: "₦58,900",
		lastPurchase: "January 17, 2026",
		status: "active",
	},
	{
		id: "16",
		name: "Brian Lewis",
		avatar: "BL",
		email: "brian.lewis@email.com",
		phone: "+1 (555) 678-9013",
		joinDate: "December 1, 2024",
		totalOrders: 3,
		totalSpent: "₦12,400",
		lastPurchase: "January 3, 2026",
		status: "active",
	},
	{
		id: "17",
		name: "Nicole Walker",
		avatar: "NW",
		email: "nicole.walker@email.com",
		phone: "+1 (555) 789-0124",
		joinDate: "December 15, 2024",
		totalOrders: 7,
		totalSpent: "₦33,600",
		lastPurchase: "January 12, 2026",
		status: "active",
	},
	{
		id: "18",
		name: "Jason Hall",
		avatar: "JH",
		email: "jason.hall@email.com",
		phone: "+1 (555) 890-1235",
		joinDate: "January 2, 2025",
		totalOrders: 5,
		totalSpent: "₦21,800",
		lastPurchase: "January 15, 2026",
		status: "active",
	},
	{
		id: "19",
		name: "Rachel Allen",
		avatar: "RA",
		email: "rachel.allen@email.com",
		phone: "+1 (555) 901-2346",
		joinDate: "January 18, 2025",
		totalOrders: 0,
		totalSpent: "₦0",
		lastPurchase: "N/A",
		status: "pending",
	},
	{
		id: "20",
		name: "Timothy Young",
		avatar: "TY",
		email: "timothy.young@email.com",
		phone: "+1 (555) 012-3457",
		joinDate: "February 5, 2025",
		totalOrders: 10,
		totalSpent: "₦47,200",
		lastPurchase: "January 16, 2026",
		status: "active",
	},
	{
		id: "21",
		name: "Kimberly King",
		avatar: "KK",
		email: "kimberly.king@email.com",
		phone: "+1 (555) 123-4569",
		joinDate: "March 10, 2025",
		totalOrders: 8,
		totalSpent: "₦36,500",
		lastPurchase: "January 14, 2026",
		status: "active",
	},
	{
		id: "22",
		name: "Steven Wright",
		avatar: "SW",
		email: "steven.wright@email.com",
		phone: "+1 (555) 234-5680",
		joinDate: "April 22, 2025",
		totalOrders: 4,
		totalSpent: "₦18,700",
		lastPurchase: "January 10, 2026",
		status: "active",
	},
	{
		id: "23",
		name: "Laura Scott",
		avatar: "LS",
		email: "laura.scott@email.com",
		phone: "+1 (555) 345-6781",
		joinDate: "May 8, 2025",
		totalOrders: 13,
		totalSpent: "₦54,300",
		lastPurchase: "January 17, 2026",
		status: "active",
	},
	{
		id: "24",
		name: "Mark Green",
		avatar: "MG",
		email: "mark.green@email.com",
		phone: "+1 (555) 456-7892",
		joinDate: "June 15, 2025",
		totalOrders: 2,
		totalSpent: "₦9,800",
		lastPurchase: "October 5, 2025",
		status: "inactive",
	},
	{
		id: "25",
		name: "Angela Adams",
		avatar: "AA",
		email: "angela.adams@email.com",
		phone: "+1 (555) 567-8903",
		joinDate: "July 20, 2025",
		totalOrders: 6,
		totalSpent: "₦27,400",
		lastPurchase: "January 13, 2026",
		status: "active",
	},
	{
		id: "26",
		name: "Eric Nelson",
		avatar: "EN",
		email: "eric.nelson@email.com",
		phone: "+1 (555) 678-9014",
		joinDate: "August 3, 2025",
		totalOrders: 9,
		totalSpent: "₦41,600",
		lastPurchase: "January 15, 2026",
		status: "active",
	},
	{
		id: "27",
		name: "Melissa Carter",
		avatar: "MC",
		email: "melissa.carter@email.com",
		phone: "+1 (555) 789-0125",
		joinDate: "September 12, 2025",
		totalOrders: 1,
		totalSpent: "₦4,500",
		lastPurchase: "September 20, 2025",
		status: "inactive",
	},
	{
		id: "28",
		name: "Ryan Mitchell",
		avatar: "RM",
		email: "ryan.mitchell@email.com",
		phone: "+1 (555) 890-1236",
		joinDate: "October 28, 2025",
		totalOrders: 5,
		totalSpent: "₦22,100",
		lastPurchase: "January 11, 2026",
		status: "active",
	},
	{
		id: "29",
		name: "Heather Roberts",
		avatar: "HR",
		email: "heather.roberts@email.com",
		phone: "+1 (555) 901-2347",
		joinDate: "November 15, 2025",
		totalOrders: 3,
		totalSpent: "₦14,700",
		lastPurchase: "January 8, 2026",
		status: "pending",
	},
	{
		id: "30",
		name: "Patrick Turner",
		avatar: "PT",
		email: "patrick.turner@email.com",
		phone: "+1 (555) 012-3458",
		joinDate: "December 5, 2025",
		totalOrders: 2,
		totalSpent: "₦11,200",
		lastPurchase: "January 16, 2026",
		status: "active",
	},
];

// Create a record for easy lookup by ID (used in chat page)
export const mockCustomersById: Record<string, CustomerData> =
	Object.fromEntries(mockCustomers.map((customer) => [customer.id, customer]));

export const mockMessages: Record<string, Message[]> = {
	"1": [
		{
			id: "1",
			content: "Hi, I have a question about my order",
			timestamp: "10:30 AM",
			isAgent: false,
		},
		{
			id: "2",
			content: "Hello! I'd be happy to help. What's your question?",
			timestamp: "10:31 AM",
			isAgent: true,
		},
		{
			id: "3",
			content: "When will my order arrive?",
			timestamp: "10:32 AM",
			isAgent: false,
		},
		{
			id: "4",
			content:
				"Your order should arrive by Friday. You can track it with order #12345",
			timestamp: "10:33 AM",
			isAgent: true,
		},
		{
			id: "5",
			content: "Thanks for your help!",
			timestamp: "10:34 AM",
			isAgent: false,
		},
	],
	"2": [
		{
			id: "1",
			content: "Can you help me with my order?",
			timestamp: "10:15 AM",
			isAgent: false,
		},
		{
			id: "2",
			content: "Of course! What do you need help with?",
			timestamp: "10:16 AM",
			isAgent: true,
		},
	],
	"3": [
		{
			id: "1",
			content: "I'd like to place an order",
			timestamp: "9:45 AM",
			isAgent: false,
		},
		{
			id: "2",
			content:
				"Great! I can help you with that. What items are you interested in?",
			timestamp: "9:46 AM",
			isAgent: true,
		},
		{
			id: "3",
			content: "The premium package please",
			timestamp: "9:47 AM",
			isAgent: false,
		},
		{
			id: "4",
			content: "Perfect, let me process that for you...",
			timestamp: "9:48 AM",
			isAgent: true,
		},
		{
			id: "5",
			content: "Perfect, I'll proceed with the purchase",
			timestamp: "9:49 AM",
			isAgent: false,
		},
	],
	"4": [
		{
			id: "1",
			content: "Is the product still available?",
			timestamp: "8:20 AM",
			isAgent: false,
		},
	],
	"5": [
		{
			id: "1",
			content: "I received my order today, thank you!",
			timestamp: "2:30 PM",
			isAgent: false,
		},
		{
			id: "2",
			content: "That's great to hear! Is everything okay with your order?",
			timestamp: "2:31 PM",
			isAgent: true,
		},
		{
			id: "3",
			content: "Yes, everything is perfect!",
			timestamp: "2:32 PM",
			isAgent: false,
		},
		{
			id: "4",
			content: "Thank you for choosing us!",
			timestamp: "2:33 PM",
			isAgent: true,
		},
		{
			id: "5",
			content: "Thank you for the quick response",
			timestamp: "2:34 PM",
			isAgent: false,
		},
	],
};

const PRODUCT_IMAGE_URL =
	"https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?q=80&w=988&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D";

export const mockProducts: Product[] = [
	{
		id: "1",
		name: "Premium Wireless Headphones",
		image: PRODUCT_IMAGE_URL,
		price: "₦25,000",
		stock: 45,
		category: "Electronics",
		description:
			"High-quality wireless headphones with active noise cancellation",
		sku: "PROD-001",
	},
	{
		id: "2",
		name: "Smart Watch Pro",
		image: PRODUCT_IMAGE_URL,
		price: "₦18,500",
		stock: 32,
		category: "Wearables",
		description: "Feature-rich smartwatch with health tracking",
		sku: "PROD-002",
	},
	{
		id: "3",
		name: "USB-C Fast Charger",
		image: PRODUCT_IMAGE_URL,
		price: "₦8,500",
		stock: 120,
		category: "Accessories",
		description: "Ultra-fast USB-C charging adapter",
		sku: "PROD-003",
	},
	{
		id: "4",
		name: "Portable SSD 1TB",
		image: PRODUCT_IMAGE_URL,
		price: "₦35,000",
		stock: 15,
		category: "Storage",
		description: "Lightning-fast portable solid state drive",
		sku: "PROD-004",
	},
	{
		id: "5",
		name: "Gaming Mouse",
		image: PRODUCT_IMAGE_URL,
		price: "₦12,000",
		stock: 67,
		category: "Electronics",
		description: "High-precision gaming mouse with custom sensitivity",
		sku: "PROD-005",
	},
	{
		id: "6",
		name: "Mechanical Keyboard",
		image: PRODUCT_IMAGE_URL,
		price: "₦22,500",
		stock: 5,
		category: "Electronics",
		description: "RGB mechanical keyboard with cherry switches",
		sku: "PROD-006",
	},
	{
		id: "7",
		name: "4K Webcam",
		image: PRODUCT_IMAGE_URL,
		price: "₦28,000",
		stock: 8,
		category: "Electronics",
		description: "Professional 4K streaming webcam",
		sku: "PROD-007",
	},
	{
		id: "8",
		name: "Wireless Charger Pad",
		image: PRODUCT_IMAGE_URL,
		price: "₦6,500",
		stock: 89,
		category: "Accessories",
		description: "Qi-compatible wireless charging pad",
		sku: "PROD-008",
	},
];

export const mockOrders: Order[] = [
	{
		id: "1",
		orderNumber: "ORD-001",
		customerName: "Sarah Johnson",
		customerEmail: "sarah.johnson@email.com",
		items: [
			{ productId: "1", productName: "Premium Wireless Headphones", quantity: 1, price: "₦25,000" },
			{ productId: "3", productName: "USB-C Fast Charger", quantity: 2, price: "₦17,000" },
		],
		totalAmount: "₦42,000",
		status: "delivered",
		paymentStatus: "paid",
		orderDate: "January 10, 2026",
		shippingAddress: "123 Main St, Lagos, Nigeria",
	},
	{
		id: "2",
		orderNumber: "ORD-002",
		customerName: "Michael Chen",
		customerEmail: "michael.chen@email.com",
		items: [
			{ productId: "2", productName: "Smart Watch Pro", quantity: 1, price: "₦18,500" },
		],
		totalAmount: "₦18,500",
		status: "shipped",
		paymentStatus: "paid",
		orderDate: "January 12, 2026",
		shippingAddress: "456 Oak Ave, Abuja, Nigeria",
	},
	{
		id: "3",
		orderNumber: "ORD-003",
		customerName: "Emma Davis",
		customerEmail: "emma.davis@email.com",
		items: [
			{ productId: "4", productName: "Portable SSD 1TB", quantity: 1, price: "₦35,000" },
			{ productId: "5", productName: "Gaming Mouse", quantity: 1, price: "₦12,000" },
		],
		totalAmount: "₦47,000",
		status: "processing",
		paymentStatus: "paid",
		orderDate: "January 14, 2026",
		shippingAddress: "789 Pine Rd, Port Harcourt, Nigeria",
	},
	{
		id: "4",
		orderNumber: "ORD-004",
		customerName: "James Wilson",
		customerEmail: "james.wilson@email.com",
		items: [
			{ productId: "6", productName: "Mechanical Keyboard", quantity: 1, price: "₦22,500" },
		],
		totalAmount: "₦22,500",
		status: "pending",
		paymentStatus: "unpaid",
		orderDate: "January 15, 2026",
		shippingAddress: "321 Elm St, Ibadan, Nigeria",
	},
	{
		id: "5",
		orderNumber: "ORD-005",
		customerName: "Lisa Anderson",
		customerEmail: "lisa.anderson@email.com",
		items: [
			{ productId: "7", productName: "4K Webcam", quantity: 2, price: "₦56,000" },
			{ productId: "8", productName: "Wireless Charger Pad", quantity: 1, price: "₦6,500" },
		],
		totalAmount: "₦62,500",
		status: "delivered",
		paymentStatus: "paid",
		orderDate: "January 15, 2026",
		shippingAddress: "654 Maple Dr, Kano, Nigeria",
	},
	{
		id: "6",
		orderNumber: "ORD-006",
		customerName: "David Brown",
		customerEmail: "david.brown@email.com",
		items: [
			{ productId: "1", productName: "Premium Wireless Headphones", quantity: 1, price: "₦25,000" },
		],
		totalAmount: "₦25,000",
		status: "cancelled",
		paymentStatus: "refunded",
		orderDate: "January 16, 2026",
		shippingAddress: "987 Cedar Ln, Enugu, Nigeria",
	},
	{
		id: "7",
		orderNumber: "ORD-007",
		customerName: "Jennifer Martinez",
		customerEmail: "jennifer.martinez@email.com",
		items: [
			{ productId: "2", productName: "Smart Watch Pro", quantity: 1, price: "₦18,500" },
			{ productId: "3", productName: "USB-C Fast Charger", quantity: 3, price: "₦25,500" },
			{ productId: "8", productName: "Wireless Charger Pad", quantity: 2, price: "₦13,000" },
		],
		totalAmount: "₦57,000",
		status: "shipped",
		paymentStatus: "paid",
		orderDate: "January 17, 2026",
		shippingAddress: "147 Birch St, Benin City, Nigeria",
	},
	{
		id: "8",
		orderNumber: "ORD-008",
		customerName: "Robert Taylor",
		customerEmail: "robert.taylor@email.com",
		items: [
			{ productId: "5", productName: "Gaming Mouse", quantity: 2, price: "₦24,000" },
		],
		totalAmount: "₦24,000",
		status: "processing",
		paymentStatus: "paid",
		orderDate: "January 17, 2026",
		shippingAddress: "258 Walnut Ave, Jos, Nigeria",
	},
	{
		id: "9",
		orderNumber: "ORD-009",
		customerName: "Amanda White",
		customerEmail: "amanda.white@email.com",
		items: [
			{ productId: "4", productName: "Portable SSD 1TB", quantity: 1, price: "₦35,000" },
		],
		totalAmount: "₦35,000",
		status: "pending",
		paymentStatus: "unpaid",
		orderDate: "January 18, 2026",
		shippingAddress: "369 Spruce Rd, Kaduna, Nigeria",
	},
	{
		id: "10",
		orderNumber: "ORD-010",
		customerName: "Christopher Lee",
		customerEmail: "christopher.lee@email.com",
		items: [
			{ productId: "6", productName: "Mechanical Keyboard", quantity: 1, price: "₦22,500" },
			{ productId: "5", productName: "Gaming Mouse", quantity: 1, price: "₦12,000" },
		],
		totalAmount: "₦34,500",
		status: "delivered",
		paymentStatus: "paid",
		orderDate: "January 18, 2026",
		shippingAddress: "741 Ash Blvd, Abeokuta, Nigeria",
	},
];

export const mockNotifications: Notification[] = [
	{
		id: "1",
		title: "New order received",
		description: "Order #ORD-011 from Sarah Johnson for ₦45,000",
		timestamp: "2 mins ago",
		read: false,
		type: "order",
	},
	{
		id: "2",
		title: "Low stock alert",
		description: "Mechanical Keyboard (SKU: PROD-006) has only 5 units left",
		timestamp: "15 mins ago",
		read: false,
		type: "warning",
	},
	{
		id: "3",
		title: "Payment confirmed",
		description: "Payment of ₦22,500 received for order #ORD-004",
		timestamp: "1 hour ago",
		read: false,
		type: "success",
	},
	{
		id: "4",
		title: "Order shipped",
		description: "Order #ORD-007 has been shipped to Jennifer Martinez",
		timestamp: "3 hours ago",
		read: true,
		type: "info",
	},
	{
		id: "5",
		title: "New customer registered",
		description: "Rachel Allen created an account",
		timestamp: "5 hours ago",
		read: true,
		type: "info",
	},
	{
		id: "6",
		title: "Order delivered",
		description: "Order #ORD-001 was delivered successfully",
		timestamp: "1 day ago",
		read: true,
		type: "success",
	},
];
